/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.sparkysimp.verticalsearch;
import java.math.*;
/**
 * 
 */
public class Library  {
    public ArraySizePair getArraySizePair(Object[] array) {
        return new ArraySizePair((int)Math.floor((int)Math.sqrt(array.length)), (int)Math.ceil((int)Math.sqrt(array.length)));
    }
    public Object[][] ozturkTransform(Object[] array) {
        ArraySizePair sizePair = getArraySizePair(array);
        Object[][] matrix = new Object[sizePair.width()][sizePair.height()];

        for(int i = 0; i < sizePair.width(); i++) {
            for(int j = 0; j < sizePair.height(); j++) {

                matrix[i][j] = array[i * sizePair.width() + j];
            }
        }

        return matrix;
    }
    public int ozturkSearch(Object[] array, Object what) {
        return -1;
    }
}
